In [2]:
import numpy as np

In [5]:
list=[1,2,3,4]
np.array(list)

array([1, 2, 3, 4])

In [6]:
np.arange(40,55)

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.random.rand(2)

array([0.14281199, 0.40895131])

In [14]:
np.random.rand(3,3)

array([[0.85422265, 0.27701785, 0.53300082],
       [0.96132089, 0.74378738, 0.95158097],
       [0.59969265, 0.79176944, 0.58670675]])

In [15]:
np.random.randn(4,4)

array([[ 1.13805778,  1.02393422,  0.20362629,  1.47078844],
       [ 0.04026808, -0.60781736, -0.2056925 , -0.10045313],
       [ 1.96731057, -0.53096729, -1.01999163,  0.10003779],
       [ 0.47166688, -0.10283931,  0.29106347,  1.72443823]])

In [16]:
np.random.randint(0,100,5)

array([40,  4,  7, 23,  0])

In [17]:
np.random.randint(0,100,(4,4))

array([[85, 68, 75, 38],
       [ 5, 40, 35, 53],
       [50, 14, 89,  8],
       [81, 95, 57, 19]])

In [18]:
np.random.seed(42)#(you will get same random number every time and across all devices where you run this code)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [20]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
arr=arr.reshape((5,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
new=np.random.randint(0,100,(4,4))
new

array([[ 1, 87, 29, 37],
       [ 1, 63, 59, 20],
       [32, 75, 57, 21],
       [88, 48, 90, 58]])

In [31]:
new.argmax()  #gives index of that max value

14

In [32]:
new.max()

90

In [35]:
#BROADCASTING
list1=[1,2,3,4,5]
numpy1=np.arange(5,9)
numpy1[0:2]=40
numpy1

array([40, 40,  7,  8])